version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  
  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
